<?php

namespace App\Repository;

use App\Entity\Company;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithCompany($id)
    {
        // SQL
        // QueryBuilder
//        $this->createQueryBuilder('c')
//            ->leftJoin(Company::class, 'cmp')
//            ->where(['c.id' => $id]);
        // DQL
        $dql = <<<DQL
SELECT c, cmp
FROM App\Entity\Contact c
LEFT JOIN c.company cmp
WHERE c.id = :id
DQL;

        return $this->_em->createQuery($dql)
                ->setParameters(['id' => $id])
                 ->getSingleResult();
    }
}
